cookie:
  expiry_days: 1
  key: KetoMed_v0.01_20241101
  name: A_KetoMed_Cookie
credentials:
  usernames:
    admin:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: Admin
      logged_in: false
      password: $2b$12$Mz9s2Sy09QI4utCn2J8OheGX14a1kYskkQgWZBv8gfWVCTcfhkpVu
      roles:
      - viewer
